name: reflectance
channels:
- conda-forge
- defaults
dependencies:
- python=3.9
- pip
- numpy>=1.20
- scipy>=1.8
- matplotlib>=3.5
- jupyter
- jupyterlab
- ipykernel
- ipywidgets
- pandas>=1.4
- camelot-py
- python-docx
- streamlit
- pip:
  - python-certifi-win32
  - pysptools