name: reflectance
channels:
- conda-forge
- defaults
dependencies:
- python=3.9
- pip
- numpy>=1.20
- scipy>=1.8
- matplotlib>=3.5
- jupyter
- jupyterlab
- ipykernel
- ipywidgets
- pandas>=1.4
- geopandas
- pillow>=8.1
- h5py
- seaborn>=0.11
- pint
- cartopy
- verde
- spectral
- camelot-py
- python-docx
- pip:
  - geopy
  - pyproj
  - python-certifi-win32